debug: false
frame_dist_cm: 20.0
max_detection: 500
output_dir: "./outputs"
preview_fps: 3
preview_quality: 80
preview_width: 480
preview_height: 272
roi_mask: "./mask.png"
green_max_ratio: 0.5 # max green ratio to determine if a patch is not plant
tracking:
  det_w: 1280
  det_h: 720
  dist_thresh: 100
  max_object_count: 100
  max_rock_ratio: 3
  max_skip_frame: 2
  max_trace_length: 64
  min_rock_pix: 24
  max_rock_pix: 300
  min_speed_threshold: 1.0 # m/s
  min_y_motion: 0.1 # vertical portion of motion
  min_y_x_ratio: 1.618 # y/x ratio
  min_trace_length: 4 # min trace length to be considered as a rock
  allow_move_up: false
  move_up_thresh: 10
video_src: rtsp://admin:nd12345678@10.168.1.100/
vcr_path: "/opt/vcr"
camera_web_url: "javascript:void(0);"
camera_id: "001"
location: "奉节县大树镇大树村4社"
target_name: "柑子坪危岩一级专业监测"
target_tags: ["危岩", "集中农户"]
target_desc: "陡崖长约984m，分布23个危岩单体，单个危岩体积1.2～2350.7m3，总体积约7994.8m3，威胁刘家包居民集中区、汤家包居民集中区及柑子坪西侧居民区、X010县道及村级硬化公路过往车辆及行人安全。"
target_range: 7994.8
target_range_unit: "m3"
sms:
  enable: false
  phone: "13310227936"
  sender: "南地科技"
